#pragma once


enum XTERType
{
  XTER_FLAT, // 0x00
  XTER_SLOPE_N, // 0x01
  XTER_SLOPE_E, // 0x02
  XTER_SLOPE_S, // 0x03
  XTER_SLOPE_W, // 0x04
  XTER_SLOPE_NE, // 0x05
  XTER_SLOPE_SE, // 0x06
  XTER_SLOPE_SW, // 0x07
  XTER_SLOPE_NW, // 0x08
  XTER_CORNER_NE, // 0x09
  XTER_CORNER_SE, // 0xA
  XTER_CORNER_SW, // 0xB
  XTER_CORNER_NW, // 0xC
  XTER_HIGHGROUND, // 0xD
  XTER_UNUSED_0E, // 0xE
  XTER_UNUSED_0F, // 0xF
  XTER_UNDERWATER_FLAT, // 0x10
  XTER_UNDERWATER_SLOPE_N, // 0x11
  XTER_UNDERWATER_SLOPE_E,// 0x12
  XTER_UNDERWATER_SLOPE_S, // 0x13
  XTER_UNDERWATER_SLOPE_W, // 0x14
  XTER_UNDERWATER_SLOPE_NE, // 0x15
  XTER_UNDERWATER_SLOPE_SE, // 0x16
  XTER_UNDERWATER_SLOPE_SW, // 0x17
  XTER_UNDERWATER_SLOPE_NW, // 0x18
  XTER_UNDERWATER_CORNER_NE,// 0x19
  XTER_UNDERWATER_CORNER_SE, // 0x1A
  XTER_UNDERWATER_CORNER_SW,// 0x1B
  XTER_UNDERWATER_CORNER_NW,// 0x1C
  XTER_UNDERWATER_HIGHGROUND,// 0x1D
  XTER_UNUSED_1E,// 0x1E
  XTER_UNUSED_1F,// 0x1F
  XTER_WATER_SUBMERGED_FLAT,// 0x20
  XTER_WATER_SUBMERGED_SLOPE_N,// 0x21
  XTER_WATER_SUBMERGED_SLOPE_E, // 0x22
  XTER_WATER_SUBMERGED_SLOPE_S,// 0x23
  XTER_WATER_SUBMERGED_SLOPE_W,// 0x24
  XTER_WATER_SUBMERGED_SLOPE_NE,// 0x25
  XTER_WATER_SUBMERGED_SLOPE_SE,// 0x26
  XTER_WATER_SUBMERGED_SLOPE_SW,// 0x27
  XTER_WATER_SUBMERGED_SLOPE_NW,// 0x28
  XTER_WATER_SUBMERGED_CORNER_NE,// 0x29
  XTER_WATER_SUBMERGED_CORNER_SE, // 0x2A
  XTER_WATER_SUBMERGED_CORNER_SW, // 0x2B
  XTER_WATER_SUBMERGED_CORNER_NW,// 0x2C
  XTER_WATER_SUBMERGED_HIGHGROUND, // 0x2D
  XTER_UNUSED_2E, // 0x2E
  XTER_UNUSED_2F, // 0x2F
  XTER_SURFACE_WATER_FLAT, // 0x30
  XTER_SURFACE_WATER_SLOPE_N, // 0x31
  XTER_SURFACE_WATER_SLOPE_E, // 0x32
  XTER_SURFACE_WATER_SLOPE_S, // 0x33
  XTER_SURFACE_WATER_SLOPE_W, // 0x34
  XTER_SURFACE_WATER_SLOPE_NE, // 0x35
  XTER_SURFACE_WATER_SLOPE_SE, // 0x36
  XTER_SURFACE_WATER_SLOPE_SW, // 0x37
  XTER_SURFACE_WATER_SLOPE_NW, // 0x38
  XTER_SURFACE_WATER_CORNER_NE, // 0x39
  XTER_SURFACE_WATER_CORNER_SE,// 0x3A
  XTER_SURFACE_WATER_CORNER_SW, // 0x3B
  XTER_SURFACE_WATER_CORNER_NW, // 0x3C
  XTER_SURFACE_WATER_HIGHGROUND, // 0x3D
  XTER_WATERFALL, // 0x3E
  XTER_UNUSED_3F,// 0x3F
  XTER_SURFACE_WATER_CANAL_WE,// 0x40
  XTER_SURFACE_WATER_CANAL_NS, // 0x41
  XTER_SURFACE_WATER_BAY_OPEN_S, // 0x42
  XTER_SURFACE_WATER_BAY_OPEN_W, // 0x43
  XTER_SURFACE_WATER_BAY_OPEN_N, // 0x44
  XTER_SURFACE_WATER_BAY_OPEN_E // 0x45
};

#define XBLD_IS_TREE(v) (v >= XBLD_TREES_1 && v <= XBLD_TREES_7)
enum XBLDType
{
  XBLD_CLEAR, // 0x00
  XBLD_RUBBLE_1, //0x01
  XBLD_RUBBLE_2, //0x02
  XBLD_RUBBLE_3, //0x03
  XBLD_RUBBLE_4, //0x04
  XBLD_RADIOACTIVE, //0x05
  XBLD_TREES_1, //0x06
  XBLD_TREES_2, //0x07
  XBLD_TREES_3, //0x08
  XBLD_TREES_4, //0x09
  XBLD_TREES_5, //0x0A
  XBLD_TREES_6, //0x0B
  XBLD_TREES_7, //0x0C
};